#!/usr/bin/env python3
"""Merge the per-module global symbol tables into one canonical table.

Each analysis pass named DGROUP globals from its own module's point of view,
so the same offset can carry several names. This picks one canonical name per
offset (by module priority below), records the other names as "aka", and
makes names unique. Output: tools/re/symbols/merged_globals.tsv
(offset, name, type, description) plus a conflict report on stdout.
"""
import collections
import glob
import os

HERE = os.path.dirname(os.path.abspath(__file__))
SYMS = os.path.join(HERE, 'symbols')
# Engine library passes first: their names describe the low-level meaning.
PRIORITY = ['libs', '2255', '1000', '19ac', '2dbd', '365e_a', '365e_b']


def module_of(path):
    return os.path.basename(path)[len('globals_'):-len('.tsv')]


def main():
    entries = collections.defaultdict(list)  # off -> [(prio, module, name, type, desc)]
    for path in glob.glob(os.path.join(SYMS, 'globals_*.tsv')):
        mod = module_of(path)
        prio = PRIORITY.index(mod) if mod in PRIORITY else len(PRIORITY)
        for line in open(path, encoding='utf-8', errors='replace'):
            if not line.strip() or line.startswith('#'):
                continue
            cols = line.rstrip('\r\n').split('\t')
            if len(cols) < 2:
                continue
            try:
                off = int(cols[0].strip().lower().replace('0x', ''), 16)
            except ValueError:
                continue
            ctype = cols[2].strip() if len(cols) > 2 else ''
            desc = cols[3].strip() if len(cols) > 3 else ''
            entries[off].append((prio, mod, cols[1].strip(), ctype, desc))

    used = collections.Counter()
    rows = []
    conflicts = 0
    for off in sorted(entries):
        cands = sorted(entries[off])
        _, mod, name, ctype, desc = cands[0]
        others = sorted({n for _, _, n, _, _ in cands[1:] if n != name})
        if others:
            conflicts += 1
        if not ctype:
            ctype = next((t for _, _, _, t, _ in cands if t), '')
        if not desc:
            desc = next((d for _, _, _, _, d in cands if d), '')
        rows.append([off, name, ctype, desc, others, mod])
        used[name] += 1
    for r in rows:
        if used[r[1]] > 1:
            r[1] = f'{r[1]}_{r[0]:04x}'

    out = os.path.join(SYMS, 'merged_globals.tsv')
    with open(out, 'w', encoding='utf-8', newline='\n') as f:
        f.write('# Generated by tools/re/merge_symbols.py from globals_*.tsv - do not edit by hand.\n')
        for off, name, ctype, desc, others, mod in rows:
            aka = f' [aka {", ".join(others)}]' if others else ''
            f.write(f'{off:04x}\t{name}\t{ctype}\t{desc}{aka}\n')
    print(f'{len(rows)} globals, {conflicts} with alternative names -> {out}')


if __name__ == '__main__':
    main()
